# Generated by Django 5.2.6 on 2025-10-11 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=models.TextField(
                help_text="Максимум 35,000 символов (~5,000 слов)",
                validators=[django.core.validators.MaxLengthValidator(35000)],
                verbose_name="Содержимое",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(
                help_text="Максимум 200 символов",
                max_length=200,
                verbose_name="Заголовок",
            ),
        ),
    ]
